n = int(input("Enter number of elements: "))
a = [0] * n
for i in range(n):
    a[i] = int(input("Enter element: "))
print("The elements are: ", a)
a.append(100)
print("After appending 100: ", a)
a.pop()
print("After popping last element: ", a)
a.reverse()
print("After reversing", a)
a.reverse()
print("after reverting the made changes", a)
x = int(input("give the number to remove: "))
a.remove(x)
print("after removing",x, "the arrary becomes" ,a)
a.append(x)
print("adding the removed element again", a)
a.insert(int(input("Give the index to add the value to: ")),int(input("give the value to add to the list: ")))
print("after inserting the user's value at the 1 index", a)
b = [100,200,100,400,100]
print("Array b = [100,200,100,400,100]")
a.extend(b)
print("merging the list a and b in a", a)
a.remove(400)
print("removeing 400", a)
print("since this list contains many 100s we will count the number of it", a.count(100))
print("finding the index of 2h =" \
"00", a.index(200))
a.sort()
print("The array is now sorted",a)
hocux = a.copy() 
print("copying the array a into the array named hocurx")
a.clear()
print("we are clearing all the elements in a. a =",a)
print("we are not prining the array named hocurx. hocrux = ", hocux)